import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:dartz/dartz.dart';
import 'package:movie_mate/core/blocs/common_api_state.dart';
import 'package:movie_mate/core/error/failures.dart';
import 'package:movie_mate/features/home/data/models/movie_model.dart';
import 'package:movie_mate/features/home/domain/use_cases/get_trending_movies.dart';
import 'package:movie_mate/features/home/presentation/blocs/trending_movies_cubit.dart';


import 'trending_movies_cubit_test.mocks.dart'; // Generated by Mockito

@GenerateMocks([GetTrendingMovies])
void main() {
  late TrendingMoviesCubit cubit;
  late MockGetTrendingMovies mockGetTrendingMovies;

  setUp(() {
    mockGetTrendingMovies = MockGetTrendingMovies();
    cubit = TrendingMoviesCubit(
      mockGetTrendingMovies,
    );
  });

  test('initial state should be ApiInitial', () {
    // assert
    expect(cubit.state, equals(ApiInitial()));
  });

  group('GetTrendingMovies', () {
    final MovieModel tMovieModel = MovieModel(
      id: 1,
      title: 'Test Movie',
      originalTitle: 'Test Movie Original',
      overview: 'Test Overview',
      posterPath: 'test_poster_path',
      backdropPath: 'test_backdrop_path',
      genreIds: [1, 2],
      popularity: 10.0,
      releaseDate: '2024-01-01',
      voteAverage: 8.0,
      voteCount: 100,
      adult: false,
      video: false,
      originalLanguage: 'en',
    );
    final tTrendingMovies = List.filled(15, tMovieModel);

    blocTest<TrendingMoviesCubit, CommonApiState>(
      'should emit [ApiSuccess] when data is successfully fetched',
      build: () {
        when(mockGetTrendingMovies(params: anyNamed('params'))).thenAnswer((_) async => Right(tTrendingMovies));
        return cubit;
      },
      act: (cubit) => cubit.fetchMovies(),
      expect: () => [
        ApiSuccess(response: tTrendingMovies),
      ],
    );

    blocTest<TrendingMoviesCubit, CommonApiState>(
      'should emit [ApiError] when data fetch fails with ServerFailure',
      build: () {
        when(mockGetTrendingMovies(params: anyNamed("params"))).thenAnswer((_) async => const Left(ServerFailure(error: 'SERVER_FAILURE')));
        return cubit;
      },
      act: (cubit) => cubit.fetchMovies(),
      expect: () => [ const ApiError(message: 'SERVER_FAILURE')],
    );

    blocTest<TrendingMoviesCubit, CommonApiState>(
      'should emit [ApiError] with a proper message for Unknown Exception',
      build: () {
        when(mockGetTrendingMovies(params: anyNamed('params'))).thenAnswer((_) async => Left(CacheFailure()));
        return cubit;
      },
      act: (cubit) => cubit.fetchMovies(),
      expect: () => [const ApiError(message: 'Unknown Exception')],
    );
  });
}
